blog:
  avatar: https://avatars.githubusercontent.com/u/195545824?v=4
  name: Title
  sname: Title
  description: Des.
  favicon: static/favicon.ico
  theme:
    mode: dark
    primary_color: '#e74c3c'
    dark_bg: '#121212'
    light_bg: '#f5f7fa'
articles:
- id: '4'
  title: 弑杀
  date: '2026-01-04'
  tags:
  - bug
  content:
  - 暂无简介
  url: article/4.html
  verticalTitle: 弑杀
specials:
- id: '5'
  title: Special
  date: '2026-01-04'
  tags:
  - special
  content:
  - 暂无简介
  url: article/5.html
  verticalTitle: Special
floating_menu:
- tag: about
  display: 关于
- tag: contact
  display: 联系
special_config:
  top: true
  view:
    RF_Information: Text
    RF_Link: Link
    Copyright: ©
    C_Link: Link
    Total_time: 2026.01.01
    Others: 其他说明文本
