blog:
  avatar: https://avatars.githubusercontent.com/u/195545824?v=4
  name: VaLog
  description: 个人技术博客
  favicon: static/favicon.ico
  theme:
    mode: dark
    primary_color: '#e74c3c'
    dark_bg: '#121212'
    light_bg: '#f5f7fa'
articles:
- id: '2'
  title: Title
  date: '2026-01-03'
  tags:
  - bug
  summary: zzz
  url: article/2.html
  verticalTitle: bug
- id: '1'
  title: Test
  date: '2026-01-02'
  tags:
  - question
  summary: Test
  url: article/1.html
  verticalTitle: question
specials: []
floating_menu:
- tag: about
  display: 关于
- tag: contact
  display: 联系
